# Порт из guillaumemeyer/watermarks-remover (MIT, Copyright (c) 2026 Guillaume Meyer),
# коммит f10efaa7efc75591b4744cc1d885874a79f5f7ee. Адаптация: русский вывод, конвенции humanizer-ru, selftest.
"""C2PA/AI-метаданные в PNG и JPEG: осмотр и снятие (stdlib).

Порт image_meta.py из watermarks-remover. PNG: чанки caBX/juMB/c2*,
tEXt/zTXt/iTXt/eXIf с AI-подсказками; JPEG: APP11 (JUMBF/C2PA), APP1/2/13/14.
Опциональные c2patool/exiftool подхватываются, если стоят в PATH.
"""
import re
import struct
import subprocess
import zlib
from pathlib import Path

from common_fm import preexec, safe_arg, safe_write_bytes, which

PNG_SIG = b"\x89PNG\r\n\x1a\n"
JPEG_SOI = b"\xff\xd8"

C2PA_MARKERS = (b"c2pa", b"C2PA", b"jumb", b"JUMB", b"c2ma", b"contentcredentials",
                b"contentauth", b"cai:", b"http://ns.adobe.com/xmp/InstanceID/")
AI_META_HINTS = (b"c2pa", b"C2PA", b"contentcredentials", b"ContentCredentials",
                 b"digitalSourceType", b"trainedAlgorithmicMedia",
                 b"compositeWithTrainedAlgorithmicMedia", b"algorithmicMedia",
                 b"AIGC", b"aigc", b"AI generated", b"Generated by", b"Claude",
                 b"Anthropic", b"OpenAI", b"SynthID", b"dcterms:provenance")


def detect_format(data):
    if data.startswith(PNG_SIG):
        return "png"
    if data.startswith(JPEG_SOI):
        return "jpeg"
    return "unknown"


def _hits(blob, needles):
    low = blob.lower()
    out = []
    for n in needles:
        if n.lower() in low:
            out.append(n.decode("ascii", errors="replace"))
    return out


def inspect_png(data):
    findings, has_c2pa, has_ai = [], False, False
    if not data.startswith(PNG_SIG):
        return False, False, ["не PNG"]
    pos = 8
    while pos + 8 <= len(data):
        length = struct.unpack(">I", data[pos:pos + 4])[0]
        ctype = data[pos + 4:pos + 8]
        cs, ce = pos + 8, pos + 8 + length
        if ce + 4 > len(data):
            findings.append("обрезанный чанк %r" % ctype)
            break
        payload = data[cs:ce]
        name = ctype.decode("latin-1", errors="replace")
        if ctype in (b"caBX", b"juMB", b"jumb") or ctype.startswith(b"c2"):
            has_c2pa = True
            findings.append("PNG-чанк %s (возможный C2PA-контейнер)" % name)
        if ctype in (b"tEXt", b"zTXt", b"iTXt", b"eXIf"):
            h = _hits(payload, AI_META_HINTS + C2PA_MARKERS)
            if h:
                has_ai = True
                if any(x.lower() in ("c2pa", "contentcredentials", "jumb") for x in h):
                    has_c2pa = True
                findings.append("PNG %s: %s" % (name, ", ".join(h[:8])))
        if ctype == b"IEND":
            break
        pos = ce + 4
    whole = _hits(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append("байт-скан C2PA: %s" % ", ".join(whole[:6]))
    return has_c2pa, has_ai or has_c2pa, findings


def inspect_jpeg(data):
    findings, has_c2pa, has_ai = [], False, False
    if not data.startswith(JPEG_SOI):
        return False, False, ["не JPEG"]
    i, n = 2, len(data)
    while i + 4 <= n:
        if data[i] != 0xFF:
            i += 1
            continue
        while i < n and data[i] == 0xFF:
            i += 1
        if i >= n:
            break
        marker = data[i]
        i += 1
        if marker in (0xD8, 0xD9):
            continue
        if marker == 0xDA:
            break
        if 0xD0 <= marker <= 0xD7:
            continue
        if i + 2 > n:
            break
        seglen = struct.unpack(">H", data[i:i + 2])[0]
        if seglen < 2 or i + seglen > n:
            findings.append("плохая длина сегмента у маркера 0x%02X" % marker)
            break
        payload = data[i + 2:i + seglen]
        i += seglen
        if marker == 0xEB:
            has_c2pa = True
            findings.append("JPEG APP11 (JUMBF/C2PA)")
        if marker in (0xE1, 0xE2, 0xED, 0xEE, 0xEB):
            h = _hits(payload, AI_META_HINTS + C2PA_MARKERS)
            if h:
                has_ai = True
                if any(x.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth") for x in h):
                    has_c2pa = True
                findings.append("JPEG APP%d: %s" % (marker - 0xE0, ", ".join(h[:8])))
    whole = _hits(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append("байт-скан C2PA: %s" % ", ".join(whole[:6]))
    return has_c2pa, has_ai or has_c2pa, findings


def run_optional_tools(path):
    tools = {}
    c2patool = which("c2patool")
    if c2patool:
        try:
            r = subprocess.run([c2patool, safe_arg(str(path))], capture_output=True,
                               text=True, timeout=30, preexec_fn=preexec())
            out = ((r.stdout or "") + (r.stderr or "")).lower()
            no_manifest = any(p in out for p in ("no claim", "no jumbf", "no manifest",
                                                  "not found", "not a valid", "no c2pa"))
            tools["c2patool"] = {"available": True, "returncode": r.returncode,
                                 "snippet": out[:2000],
                                 "has_manifest": ("claim" in out or "c2pa" in out or "manifest" in out)
                                 and not no_manifest}
        except Exception as exc:
            tools["c2patool"] = {"available": True, "error": str(exc)}
    else:
        tools["c2patool"] = {"available": False}
    exiftool = which("exiftool")
    if exiftool:
        try:
            r = subprocess.run([exiftool, "-G1", "-a", "-s", safe_arg(str(path))],
                               capture_output=True, text=True, timeout=30, preexec_fn=preexec())
            interesting = [ln for ln in (r.stdout or "").splitlines()
                           if re.search(r"c2pa|content.?credential|AIGC|digitalSource|XMP|EXIF|IPTC|jumb", ln, re.I)]
            tools["exiftool"] = {"available": True, "interesting_lines": interesting[:50]}
        except Exception as exc:
            tools["exiftool"] = {"available": True, "error": str(exc)}
    else:
        tools["exiftool"] = {"available": False}
    return tools


def inspect_image(path, synthid_dir=None):
    data = Path(path).read_bytes()
    fmt = detect_format(data)
    if fmt == "png":
        has_c2pa, has_ai, findings = inspect_png(data)
    elif fmt == "jpeg":
        has_c2pa, has_ai, findings = inspect_jpeg(data)
    else:
        has_c2pa, has_ai, findings = False, False, ["неподдерживаемый формат (PNG/JPEG)"]
    tools = run_optional_tools(Path(path))
    ct = tools.get("c2patool") or {}
    if ct.get("has_manifest"):
        has_c2pa = True
        findings.append("c2patool сообщает C2PA-манифест")
    return {"path": str(path), "format": fmt, "has_c2pa": has_c2pa,
            "has_ai_metadata": has_ai, "findings": findings, "tools": tools,
            "synthid": None}


def _png_chunk(ctype, payload):
    crc = zlib.crc32(ctype)
    crc = zlib.crc32(payload, crc) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + ctype + payload + struct.pack(">I", crc)


def strip_png(data, strip_all_text=True):
    if not data.startswith(PNG_SIG):
        raise ValueError("не PNG")
    actions, out, pos = [], bytearray(PNG_SIG), 8
    while pos + 8 <= len(data):
        length = struct.unpack(">I", data[pos:pos + 4])[0]
        ctype = data[pos + 4:pos + 8]
        cs, ce = pos + 8, pos + 8 + length
        if ce + 4 > len(data):
            break
        payload, crc_bytes = data[cs:ce], data[ce:ce + 4]
        pos = ce + 4
        name = ctype.decode("latin-1", errors="replace")
        drop = False
        if ctype in (b"eXIf", b"caBX", b"juMB", b"jumb") or ctype.startswith(b"c2"):
            drop = True
            actions.append("снят чанк %s" % name)
        elif ctype in (b"tEXt", b"zTXt", b"iTXt"):
            if strip_all_text or _hits(payload, AI_META_HINTS + C2PA_MARKERS):
                drop = True
                actions.append("снят чанк %s" % name)
        elif _hits(ctype + payload, C2PA_MARKERS) and ctype not in (
                b"IHDR", b"IDAT", b"IEND", b"PLTE", b"tRNS", b"gAMA", b"pHYs", b"sRGB", b"cHRM", b"iCCP"):
            drop = True
            actions.append("снят чанк %s (C2PA в содержимом)" % name)
        if not drop:
            out.extend(struct.pack(">I", length) + ctype + payload + crc_bytes)
        if ctype == b"IEND":
            break
    if not actions:
        actions.append("метаданных не найдено")
    return bytes(out), actions


def strip_jpeg(data, strip_all_app=True):
    if not data.startswith(JPEG_SOI):
        raise ValueError("не JPEG")
    actions, out, i, n = [], bytearray(JPEG_SOI), 2, len(data)
    while i < n:
        if data[i] != 0xFF:
            out.extend(data[i:])
            actions.append("скопирован остаток после немаркерного байта")
            break
        while i < n and data[i] == 0xFF:
            i += 1
        if i >= n:
            break
        marker = data[i]
        i += 1
        if marker == 0xD9:
            out.extend(b"\xff\xd9")
            break
        if marker == 0xD8:
            continue
        if 0xD0 <= marker <= 0xD7:
            out.extend(bytes([0xFF, marker]))
            continue
        if marker == 0xDA:
            out.extend(b"\xff\xda")
            out.extend(data[i:])
            actions.append("сохранён энтропийный поток (SOS→EOF)")
            break
        if i + 2 > n:
            break
        seglen = struct.unpack(">H", data[i:i + 2])[0]
        if seglen < 2 or i + seglen > n:
            out.extend(data[i - 2:])
            actions.append("обрезанный сегмент; скопирован остаток")
            break
        payload = data[i + 2:i + seglen]
        next_i = i + seglen
        keep, drop = False, False
        if 0xE0 <= marker <= 0xEF:
            if marker == 0xEB:
                drop = True
                actions.append("снят APP11 (C2PA/JUMBF)")
            elif strip_all_app and marker != 0xE0:
                drop = True
                actions.append("снят APP%d" % (marker - 0xE0))
            elif _hits(payload, AI_META_HINTS + C2PA_MARKERS):
                drop = True
                actions.append("снят APP%d (AI/C2PA-маркеры)" % (marker - 0xE0))
            else:
                keep = True
        elif marker == 0xFE:
            drop = True
            actions.append("снят COM-комментарий")
        else:
            keep = True
        if keep and not drop:
            out.extend(bytes([0xFF, marker]))
            out.extend(data[i:i + seglen])
        i = next_i
    if not actions:
        actions.append("метаданных не найдено")
    return bytes(out), actions


def clean_image(path, dest, strip_all_metadata=True):
    data = Path(path).read_bytes()
    fmt = detect_format(data)
    if fmt == "png":
        cleaned, actions = strip_png(data, strip_all_text=strip_all_metadata)
    elif fmt == "jpeg":
        cleaned, actions = strip_jpeg(data, strip_all_app=strip_all_metadata)
    else:
        raise ValueError("неподдерживаемый формат: %s" % fmt)
    safe_write_bytes(dest, cleaned)
    exiftool = which("exiftool")
    if exiftool and strip_all_metadata:
        try:
            subprocess.run([exiftool, "-all=", "-overwrite_original", safe_arg(str(dest))],
                           capture_output=True, text=True, timeout=60, check=False,
                           preexec_fn=preexec())
            actions.append("прогон exiftool -all=")
        except Exception as exc:
            actions.append("exiftool не сработал: %s" % exc)
    after = inspect_image(dest)
    return {"input": str(path), "output": str(dest), "format": fmt, "actions": actions,
            "bytes_in": len(data), "bytes_out": Path(dest).stat().st_size,
            "still_has_c2pa": after["has_c2pa"], "still_has_ai_metadata": after["has_ai_metadata"],
            "post_findings": after["findings"]}
