#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Round-trip тесты файлового слоя scripts/filemarks/.

Всё собирается в памяти и во временных каталогах:
  - минимальный PNG (IHDR/caBX/tEXt/IDAT/IEND) с ручной упаковкой чанков;
  - DOCX и ODT — это zip-контейнеры, которые тест создаёт через zipfile;
  - zip-бомба — валидный DOCX, у которого в central directory и local header
    записи docProps/core.xml завышен uncompressed size.

Проверяется главный контракт filemarks: clean должен давать файл, для
которого inspect больше не находит меток, и при этом полезная нагрузка
(пиксельные данные PNG / document.xml DOCX / content.xml ODT) сохраняется
байт-в-байт. Плюс проверяется отказ при zip-бомбе.
"""

import io
import os
import struct
import sys
import tempfile
import unittest
import zipfile
import zlib
from pathlib import Path

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(ROOT, "scripts")
FILEMARKS = os.path.join(SCRIPTS, "filemarks")
for p in (FILEMARKS, SCRIPTS):
    if p not in sys.path:
        sys.path.insert(0, p)

import container_meta  # noqa: E402
import image_meta  # noqa: E402
import text_layer  # noqa: E402

MAX_ZIP = container_meta.MAX_ZIP_DECOMPRESSED_BYTES


def _png_chunk(ctype, payload):
    crc = zlib.crc32(ctype)
    crc = zlib.crc32(payload, crc) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + ctype + payload + struct.pack(">I", crc)


def _minimal_png():
    chunks = (
        (b"IHDR", struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0)),
        (b"caBX", b"c2pa manifest data"),
        (b"tEXt", b"Generated by OpenAI"),
        (b"IDAT", zlib.compress(b"\x00\xff\x00\x00")),
        (b"IEND", b""),
    )
    out = b"\x89PNG\r\n\x1a\n"
    for ctype, payload in chunks:
        out += _png_chunk(ctype, payload)
    return out


def _docx_with_ai_metadata():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("word/document.xml",
                    "<w:document><w:body><w:p/></w:body></w:document>")
        zf.writestr("customXml/item1.xml", "<c2pa/>")
        zf.writestr("docProps/core.xml", "<dc:creator>Claude</dc:creator>")
        zf.writestr("docProps/app.xml", "<Application>Gemini</Application>")
    return buf.getvalue()


def _odt_with_ai_metadata():
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("mimetype", "application/vnd.oasis.opendocument.text",
                    compress_type=zipfile.ZIP_STORED)
        zf.writestr("content.xml", "<office:document-content/>")
        zf.writestr("meta.xml",
                    "<office:meta><meta:generator>Claude</meta:generator></office:meta>")
        zf.writestr("META-INF/manifest.xml",
                    '<manifest:manifest xmlns:manifest="urn:oasis">'
                    '<manifest:file-entry manifest:full-path="content.xml"/>'
                    '<manifest:file-entry manifest:full-path="c2pa.json"/>'
                    "</manifest:manifest>")
    return buf.getvalue()


def _patch_entry_uncompressed_size(data, entry_name, fake_size):
    """Патчит uncompressed size в local header и central directory одной записи."""
    data = bytearray(data)
    name = entry_name.encode("utf-8")
    pos = 0
    while pos + 30 <= len(data) and data[pos:pos + 4] == b"PK\x03\x04":
        nlen = struct.unpack_from("<H", data, pos + 26)[0]
        elen = struct.unpack_from("<H", data, pos + 28)[0]
        if data[pos + 30:pos + 30 + nlen] == name:
            struct.pack_into("<I", data, pos + 22, fake_size)
        csize = struct.unpack_from("<I", data, pos + 18)[0]
        pos = pos + 30 + nlen + elen + csize
    pos = data.find(b"PK\x01\x02")
    while pos >= 0 and pos + 46 <= len(data):
        nlen = struct.unpack_from("<H", data, pos + 28)[0]
        elen = struct.unpack_from("<H", data, pos + 30)[0]
        clen = struct.unpack_from("<H", data, pos + 32)[0]
        if data[pos + 46:pos + 46 + nlen] == name:
            struct.pack_into("<I", data, pos + 24, fake_size)
        pos = pos + 46 + nlen + elen + clen
    return bytes(data)


def _docx_zip_bomb():
    """Валидный DOCX, у которого docProps/core.xml обещает > MAX_ZIP байт."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_STORED) as zf:
        zf.writestr("word/document.xml", "<w:document/>")
        zf.writestr("docProps/core.xml", "<x/>")
    return _patch_entry_uncompressed_size(
        buf.getvalue(), "docProps/core.xml", MAX_ZIP + 1)


class TestFilemarksPNG(unittest.TestCase):
    def test_inspect_finds_c2pa_and_ai_text_chunk(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "x.png"
            src.write_bytes(_minimal_png())
            rep = image_meta.inspect_image(src)
            self.assertTrue(rep["has_c2pa"], rep["findings"])
            self.assertTrue(rep["has_ai_metadata"], rep["findings"])

    def test_clean_removes_metadata_and_keeps_pixel_payload(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "x.png"
            dst = Path(td) / "x.cleaned.png"
            src.write_bytes(_minimal_png())
            rep = image_meta.clean_image(src, dst)
            self.assertFalse(rep["still_has_c2pa"], rep["actions"])
            self.assertFalse(rep["still_has_ai_metadata"], rep["post_findings"])
            cleaned = dst.read_bytes()
            original = src.read_bytes()
            self.assertTrue(cleaned.startswith(b"\x89PNG\r\n\x1a\n"))
            self.assertEqual(
                original[original.index(b"IDAT"):original.index(b"IEND")],
                cleaned[cleaned.index(b"IDAT"):cleaned.index(b"IEND")])
            self.assertNotIn(b"caBX", cleaned)
            self.assertNotIn(b"Generated by OpenAI", cleaned)


class TestFilemarksDOCXODT(unittest.TestCase):
    def test_docx_inspect_clean_roundtrip(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "x.docx"
            dst = Path(td) / "x.cleaned.docx"
            src.write_bytes(_docx_with_ai_metadata())
            rep = container_meta.inspect_container(src)
            self.assertTrue(rep["has_c2pa"], rep["findings"])
            self.assertTrue(rep["has_ai_metadata"], rep["findings"])
            cleaned = container_meta.clean_container(src, dst)
            self.assertFalse(cleaned["still_has_c2pa"], cleaned["actions"])
            self.assertFalse(cleaned["still_has_ai_metadata"], cleaned["post_findings"])
            with zipfile.ZipFile(dst) as zf:
                names = set(zf.namelist())
                payload = zf.read("word/document.xml")
                core = zf.read("docProps/core.xml")
                app = zf.read("docProps/app.xml")
            self.assertFalse(any(n.startswith("customXml/") for n in names))
            self.assertEqual(payload,
                             "<w:document><w:body><w:p/></w:body></w:document>".encode("utf-8"))
            self.assertNotIn(b"Claude", core)
            self.assertNotIn(b"Gemini", app)

    def test_odt_inspect_clean_roundtrip(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "x.odt"
            dst = Path(td) / "x.cleaned.odt"
            src.write_bytes(_odt_with_ai_metadata())
            rep = container_meta.inspect_container(src)
            self.assertTrue(rep["has_c2pa"], rep["findings"])
            self.assertTrue(rep["has_ai_metadata"], rep["findings"])
            cleaned = container_meta.clean_container(src, dst)
            self.assertFalse(cleaned["still_has_c2pa"], cleaned["actions"])
            self.assertFalse(cleaned["still_has_ai_metadata"], cleaned["post_findings"])
            with zipfile.ZipFile(dst) as zf:
                self.assertNotIn(b"c2pa.json", zf.read("META-INF/manifest.xml"))
                self.assertNotIn(b"Claude", zf.read("meta.xml"))
                self.assertEqual(zf.read("content.xml"),
                                 "<office:document-content/>".encode("utf-8"))
                self.assertEqual(zf.read("mimetype"),
                                 "application/vnd.oasis.opendocument.text".encode("utf-8"))


class TestTextLayerA(unittest.TestCase):
    def test_clean_text_layer_removes_zero_width_and_soft_hyphen(self):
        if not text_layer.DETECTOR_OK:
            self.skipTest("check_markers не импортирован")
        # Строку собираем через chr(), чтобы в исходнике теста не было
        # самих невидимых символов: тогда self-scan --scan честно его не
        # замечает. В памяти получаются настоящие U+200B и U+00AD.
        zws = chr(0x200B)
        shy = chr(0x00AD)
        text = "сло" + zws + "во и мягкий" + shy + "перенос"
        cleaned, n = text_layer.clean_text_layer(text)
        self.assertEqual(n, 2)
        self.assertNotIn(zws, cleaned)
        self.assertNotIn(shy, cleaned)


class TestFilemarksZipBomb(unittest.TestCase):
    def test_inspect_zip_bomb_is_rejected_as_error(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "bomb.docx"
            src.write_bytes(_docx_zip_bomb())
            rep = container_meta.inspect_container(src)
            self.assertFalse(rep["has_c2pa"])
            self.assertFalse(rep["has_ai_metadata"])
            self.assertTrue(any("превышает лимит" in f for f in rep["findings"]),
                            rep["findings"])

    def test_clean_zip_bomb_raises_value_error(self):
        with tempfile.TemporaryDirectory() as td:
            src = Path(td) / "bomb.docx"
            dst = Path(td) / "bomb.cleaned.docx"
            src.write_bytes(_docx_zip_bomb())
            with self.assertRaises(ValueError):
                container_meta.clean_container(src, dst)


if __name__ == "__main__":
    unittest.main()
